# Pipeline configuration parameters

# Input files
[input]
gene_list_file = "example/data/gene_ranks_ihs-1000kb_1kgp_afr.txt"
gene_set = "example/vips/temp_inter_coronaviruses_may2020" # set of disease genes or VIPs.
gene_coords_file = "example/data/gene_coords_ensembl_v69.txt"
factors_file = "example/data/factors.txt"

# Input filtering
valid_genes_file = "example/data/valid_genes.txt" # used to filter the gene list, e.g. only keep protein coding (CDS)
hgnc_file = "example/data/ensembl_HGNC_file.txt" # Optional file used to primarily filter out HLA
special_filtered_genes = ["HLA", "OR", "HIST"]

# Output configuration
[output]
directory = "results"
save_intermediate = false

# Analysis parameters
[analysis]
min_distance = 300000
tolerance_range = 0.5
max_rep = 10
flip = false
cluster_distance = 500000
num_threads = 6 # Number of threads to use for parallel processing

# Bootstrap parameters
[bootstrap]
run = true
iterations = 10
runs = 10  # Number of bootstrap runs to perform
simultaneous_runs = 25

# FDR parameters
[fdr]
run = true
number = 10

# Population parameters
[population]

# Threshold parameters
[thresholds]
# rank_values = [
#     5000, 4000, 3000, 2500, 2000, 1500, 1000, 900, 800, 700,
#     600, 500, 450, 400, 350, 300, 250, 200, 150, 100,
#     90, 80, 70, 60, 50, 40, 30, 25, 20, 15, 10
# ]
rank_values = [
    100, 90, 80, 70, 60, 50, 40, 30, 20, 10
]