[input]
gene_list_file = "example/data/gene_ranks_ihs-1000kb_1kgp_afr.txt"
gene_set = "example/vips/temp_inter_rsv_march2017"
gene_coords_file = "example/data/gene_coords_ensembl_v69.txt"
factors_file = "example/data/factors.txt"
valid_genes_file = "example/data/valid_genes.txt"
hgnc_file = "example/data/ensembl_HGNC_file.txt"
special_filtered_genes = [
    "HLA",
    "OR",
    "HIST",
]

[output]
directory = "results"
save_intermediate = false

[analysis]
min_distance = 300000
tolerance_range = 0.5
max_rep = 10
flip = false
cluster_distance = 500000
num_threads = 4

[bootstrap]
run = true
iterations = 100
runs = 1
simultaneous_runs = 25

[fdr]
run = true
number = 10
shuffling_segments = 10
interrupted = false

[sweep]
prefix = "all_ihsfreqafr_ranks"
sizes = [
    "50kb",
    "100kb",
    "200kb",
    "500kb",
    "1000kb",
]
count = false
run_count = true

[population]
groups = [
    "AFR",
    "AFR",
    "AFR",
    "AFR",
    "AFR",
]
interest = "ESN"

[threshold]
list = [
    5000,
    4000,
    3000,
    2500,
    2000,
    1500,
    1000,
    900,
    800,
    700,
    600,
    500,
    450,
    400,
    350,
    300,
    250,
    200,
    150,
    100,
    90,
    80,
    70,
    60,
    50,
    40,
    30,
    25,
    20,
    15,
    10,
]
